version: "3.9"

services:
  db:
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    command: >
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306

  migrator:
    image: flyway/flyway:latest
    command: >
      migrate
      -user=docker
      -password=docker
      -url=jdbc:mysql://mysql_host/test_db
      -locations=filesystem:./sql
    volumes:
      - ./migrate/sql:/flyway/sql:ro
    depends_on:
      - db
    restart: on-failure
